### ISSUE TITLE
Name mismatch for stored procedure

### ISSUE THREAD

**Issue by gurpreetaror** [TimCorey/Log4netTutorial#2]
The stored procedure name in app.config file is procLog_Insert whereas in SQL Scripts the name is procLogs_Insert.  Users who are directly copying code from here can have some trouble since their logs table would not be reached due to stored procedure name mismatch.

**Comment by TimCorey** [comment]
Thanks for pointing that out. I fixed the issue in commit 6517f10cbd98a20b429a520e5942a8727f7d8896
